// build-3d-page.mjs — bundles the shared pet-3d scene into a self-contained
// HTML page served inside the mobile WebView (Android mechanism, R2-P3D).
//
// WHY (documented decision in artifacts/r2p3d/R2P3D_3D_STAGE_ARCHITECTURE.md):
// expo-gl's CMake object paths exceed CMake's 250-char limit under pnpm's deep
// store layout on Windows (ninja "build.ninja still dirty"), so the audited
// Android 3D mechanism is react-native-webview + three. The SAME @pli/pet-3d
// asset + orbit math are bundled here, so 豆豆/咪咪 stay identical to the web.
//
// Regenerate after touching packages/pet-3d/src: `pnpm --dir apps/mobile build:3d-page`
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entry = resolve(root, "scripts/pet-stage-entry.ts");
const out = resolve(root, "assets/3d/pet-stage.html");

// R2P3D-R4: embed the production-candidate twin GLBs as base64 so the WebView
// (baseUrl file:///android_asset/, no HTTP server) can load them offline.
// ~6.2 MB base64 for 豆豆 + mimi is acceptable for this demo page.
const twinsDir = resolve(root, "../../packages/pet-3d/assets/twins");
const twinGlbB64 = Object.fromEntries(
  ["doudou", "mimi"].map((id) => [id, readFileSync(resolve(twinsDir, `${id}.glb`)).toString("base64")]),
);
// Injected BEFORE the bundled entry runs so the resolver can read it.
const twinGlbScript = `window.__PLI_TWIN_GLB_B64__ = ${JSON.stringify(twinGlbB64)};`;

const res = await build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["chrome80"],
  write: false,
  logLevel: "silent",
  define: { "process.env.NODE_ENV": '"production"' },
});
const js = res.outputFiles[0].text;

const html = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<style>
  html, body { margin: 0; padding: 0; width: 100%; height: 100%; background: transparent; overflow: hidden; }
  #stage { position: fixed; inset: 0; touch-action: none; }
  canvas { display: block; width: 100%; height: 100%; }
  #controls { position: fixed; right: 12px; bottom: 12px; display: none; gap: 8px; z-index: 5; }
  #controls.show { display: flex; }
  .btn {
    width: 44px; height: 44px; border-radius: 50%; border: 1px solid rgba(120,101,78,0.24);
    background: rgba(255,253,248,0.86); color: #4A3A2C; font-size: 18px; line-height: 1;
    display: flex; align-items: center; justify-content: center;
  }
  .btn:active { background: rgba(239,229,214,0.96); }
</style>
</head>
<body>
  <div id="stage"></div>
  <div id="controls" aria-label="3D 视图控制">
    <button type="button" class="btn" aria-label="缩小" onclick="zoom(false)">−</button>
    <button type="button" class="btn" aria-label="放大" onclick="zoom(true)">+</button>
    <button type="button" class="btn" aria-label="重置视图" onclick="resetView()">⟲</button>
  </div>
<script>
${twinGlbScript}
</script>
<script>
${js}
</script>
</html>`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, html, "utf8");
console.log(`pet-stage.html written: ${out} (${(html.length / 1024).toFixed(0)} KB)`);

// Also emit the page as an inline TypeScript string module so the release
// bundle never depends on the Android asset registry (expo-asset has no
// embedded metadata under `export:embed` on SDK 51; see R2P3D architecture doc).
const tsOut = resolve(root, "src/three/petStageHtml.ts");
mkdirSync(dirname(tsOut), { recursive: true });
writeFileSync(
  tsOut,
  `// Generated by scripts/build-3d-page.mjs — do not edit by hand.
// Self-contained WebView page (three + @pli/pet-3d) as an inline string so
// release builds never depend on Android asset-registry metadata.
export const PET_STAGE_HTML = ${JSON.stringify(html)};\n`,
  "utf8",
);
console.log("petStageHtml.ts written:", tsOut);