"""stage_h2_pet_living_model_visual_capture_model_manifest

Revision ID: 21b4b571112a
Revises: c4d8e2a71b93
Create Date: 2026-09-20 19:37:37.339689
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '21b4b571112a'
down_revision: Union[str, None] = 'c4d8e2a71b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_visual_captures',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capture_type', sa.String(length=20), nullable=False),
    sa.Column('qc_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qc_passed', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('privacy_scan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consent_visual_model_training', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_pet_visual_captures_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_visual_captures_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_visual_captures'))
    )
    op.create_index('ix_pvc_pet_created', 'pet_visual_captures', ['pet_id', 'created_at'], unique=False)
    op.create_table('pet_visual_models',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_capture_id', sa.UUID(), nullable=True),
    sa.Column('source_artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_model_version', sa.String(length=80), nullable=False),
    sa.Column('geometry_version', sa.String(length=40), nullable=False),
    sa.Column('texture_version', sa.String(length=40), nullable=False),
    sa.Column('rig_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('owner_verified', sa.Boolean(), nullable=True),
    sa.Column('identity_qc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance_kind', sa.String(length=20), nullable=False),
    sa.Column('provider_job_id', sa.String(length=120), nullable=True),
    sa.Column('artifact_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_visual_models_pet_id_pets')),
    sa.ForeignKeyConstraint(['source_capture_id'], ['pet_visual_captures.id'], name=op.f('fk_pet_visual_models_source_capture_id_pet_visual_captures')),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_pet_visual_models_verified_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_visual_models')),
    sa.UniqueConstraint('pet_id', 'version', name=op.f('uq_pet_visual_models_pet_id'))
    )
    op.create_index('ix_pvm_pet_active', 'pet_visual_models', ['pet_id', 'activated_at'], unique=False)
    op.create_table('pet_visual_render_manifests',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('render_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lod_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('freshness_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['pet_visual_models.id'], name=op.f('fk_pet_visual_render_manifests_model_id_pet_visual_models')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_visual_render_manifests_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_visual_render_manifests')),
    sa.UniqueConstraint('pet_id', 'model_id', name=op.f('uq_pet_visual_render_manifests_pet_id'))
    )
    op.create_index('ix_pvrm_pet', 'pet_visual_render_manifests', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pvrm_pet', table_name='pet_visual_render_manifests')
    op.drop_table('pet_visual_render_manifests')
    op.drop_index('ix_pvm_pet_active', table_name='pet_visual_models')
    op.drop_table('pet_visual_models')
    op.drop_index('ix_pvc_pet_created', table_name='pet_visual_captures')
    op.drop_table('pet_visual_captures')
    # ### end Alembic commands ###
