"""stage_e pilot mode: invite codes, user profiles, feedback

Revision ID: 3756fdb0fb13
Revises: 48fd6864be06
Create Date: 2026-09-16 11:56:52.112024
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3756fdb0fb13'
down_revision: Union[str, None] = '48fd6864be06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=300), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('client', sa.String(length=20), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pilot_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_feedback'))
    )
    op.create_index('ix_pilot_feedback_user_time', 'pilot_feedback', ['user_id', 'created_at'], unique=False)
    op.create_table('pilot_invite_codes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_pilot_invite_codes_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_invite_codes'))
    )
    op.create_index('ix_pilot_invite_codes_code', 'pilot_invite_codes', ['code'], unique=False)
    op.create_table('pilot_user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('invite_code_id', sa.UUID(), nullable=True),
    sa.Column('organization', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_code_id'], ['pilot_invite_codes.id'], name=op.f('fk_pilot_user_profiles_invite_code_id_pilot_invite_codes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pilot_user_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_user_profiles'))
    )
    op.create_index('ix_pilot_user_profiles_user_id', 'pilot_user_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pilot_user_profiles_user_id', table_name='pilot_user_profiles')
    op.drop_table('pilot_user_profiles')
    op.drop_index('ix_pilot_invite_codes_code', table_name='pilot_invite_codes')
    op.drop_table('pilot_invite_codes')
    op.drop_index('ix_pilot_feedback_user_time', table_name='pilot_feedback')
    op.drop_table('pilot_feedback')
    # ### end Alembic commands ###
