"""v0.2 schema (PLI-004..228 stage B)

Revision ID: 54591ad33a24
Revises: 89595364188f
Create Date: 2026-09-13 04:23:25.404739
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '54591ad33a24'
down_revision: Union[str, None] = '89595364188f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_counters',
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_counters')),
    sa.UniqueConstraint('metric', 'day', name=op.f('uq_analytics_counters_metric'))
    )
    op.create_table('content_versions',
    sa.Column('content_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_versions')),
    sa.UniqueConstraint('content_key', 'version', name=op.f('uq_content_versions_content_key'))
    )
    op.create_table('incidents',
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_table('baselines',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=60), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_baselines_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baselines')),
    sa.UniqueConstraint('pet_id', 'metric', name=op.f('uq_baselines_pet_id'))
    )
    op.create_table('care_reminders',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_care_reminders_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_care_reminders_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_reminders'))
    )
    op.create_index('ix_care_reminders_due', 'care_reminders', ['pet_id', 'due_date'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('ai_inference_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_daily_summaries_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries')),
    sa.UniqueConstraint('pet_id', 'summary_date', name=op.f('uq_daily_summaries_pet_id'))
    )
    op.create_table('diary_entries',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio_artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_diary_entries_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_diary_entries_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diary_entries'))
    )
    op.create_index('ix_diary_pet_time', 'diary_entries', ['pet_id', 'entry_at'], unique=False)
    op.create_table('diet_profiles',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('current_food', sa.String(length=300), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feeding_rules', sa.Text(), nullable=False),
    sa.Column('vet_advised', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_diet_profiles_pet_id_pets')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_diet_profiles_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_profiles')),
    sa.UniqueConstraint('pet_id', name=op.f('uq_diet_profiles_pet_id'))
    )
    op.create_table('expenses',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_expenses_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_expenses_household_id_households')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_expenses_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_pet_time', 'expenses', ['pet_id', 'incurred_at'], unique=False)
    op.create_table('health_records',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_note', sa.String(length=300), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_health_records_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_health_records_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_records'))
    )
    op.create_index('ix_health_records_pet', 'health_records', ['pet_id'], unique=False)
    op.create_table('milestones',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_milestones_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_milestones_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_table('pet_friends',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('friend_pet_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_pet_friends_accepted_by_user_id_users')),
    sa.ForeignKeyConstraint(['friend_pet_id'], ['pets.id'], name=op.f('fk_pet_friends_friend_pet_id_pets')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_friends_pet_id_pets')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_pet_friends_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_friends')),
    sa.UniqueConstraint('pet_id', 'friend_pet_id', name=op.f('uq_pet_friends_pet_id'))
    )
    op.create_table('pet_identifiers',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_pet_identifiers_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_identifiers_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_identifiers')),
    sa.UniqueConstraint('pet_id', 'identifier_type', 'value', name=op.f('uq_pet_identifiers_pet_id'))
    )
    op.create_table('pet_preferences',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_pet_preferences_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_preferences_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_preferences')),
    sa.UniqueConstraint('pet_id', 'kind', 'subject', name=op.f('uq_pet_preferences_pet_id'))
    )
    op.create_table('social_interactions',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('friend_pet_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(length=40), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_social_interactions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['friend_pet_id'], ['pets.id'], name=op.f('fk_social_interactions_friend_pet_id_pets')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_social_interactions_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_interactions'))
    )
    op.create_index('ix_social_interactions_pet', 'social_interactions', ['pet_id'], unique=False)
    op.create_table('social_profiles',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('good_with_dogs', sa.String(length=20), nullable=False),
    sa.Column('good_with_cats', sa.String(length=20), nullable=False),
    sa.Column('good_with_kids', sa.String(length=20), nullable=False),
    sa.Column('good_with_strangers', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_social_profiles_pet_id_pets')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_social_profiles_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_profiles')),
    sa.UniqueConstraint('pet_id', name=op.f('uq_social_profiles_pet_id'))
    )
    op.create_table('social_reports',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('friend_pet_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reported_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_pet_id'], ['pets.id'], name=op.f('fk_social_reports_friend_pet_id_pets')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_social_reports_pet_id_pets')),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], name=op.f('fk_social_reports_reported_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_reports'))
    )
    op.create_table('training_goals',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_behavior', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_training_goals_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_training_goals_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_goals'))
    )
    op.create_table('recovery_plans',
    sa.Column('health_event_id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_recovery_plans_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('fk_recovery_plans_health_event_id_health_events')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_recovery_plans_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_plans'))
    )
    op.create_table('training_sessions',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('session_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('pet_response', sa.String(length=40), nullable=False),
    sa.Column('rewards_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_training_sessions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['goal_id'], ['training_goals.id'], name=op.f('fk_training_sessions_goal_id_training_goals')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_training_sessions_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_sessions'))
    )
    op.create_index('ix_training_sessions_pet', 'training_sessions', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_sessions_pet', table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_table('recovery_plans')
    op.drop_table('training_goals')
    op.drop_table('social_reports')
    op.drop_table('social_profiles')
    op.drop_index('ix_social_interactions_pet', table_name='social_interactions')
    op.drop_table('social_interactions')
    op.drop_table('pet_preferences')
    op.drop_table('pet_identifiers')
    op.drop_table('pet_friends')
    op.drop_table('milestones')
    op.drop_index('ix_health_records_pet', table_name='health_records')
    op.drop_table('health_records')
    op.drop_index('ix_expenses_pet_time', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('diet_profiles')
    op.drop_index('ix_diary_pet_time', table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_table('daily_summaries')
    op.drop_index('ix_care_reminders_due', table_name='care_reminders')
    op.drop_table('care_reminders')
    op.drop_table('baselines')
    op.drop_table('incidents')
    op.drop_table('content_versions')
    op.drop_table('analytics_counters')
    # ### end Alembic commands ###
