"""v0.1 core schema (PLI-211..217)

Revision ID: 89595364188f
Revises:
Create Date: 2026-09-13 03:06:11.504778
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '89595364188f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_inference_logs',
    sa.Column('capability', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_inference_logs'))
    )
    op.create_table('audit_entries',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_entries'))
    )
    op.create_index('ix_audit_household_time', 'audit_entries', ['household_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_pet_time', 'audit_entries', ['pet_id', 'occurred_at'], unique=False)
    op.create_table('households',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_table('notifications',
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    op.create_index('ix_notifications_household', 'notifications', ['household_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('household_members',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_members_household_id_households')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_household_members_invited_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_members')),
    sa.UniqueConstraint('household_id', 'user_id', name=op.f('uq_household_members_household_id'))
    )
    op.create_table('invitations',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_invitations_accepted_by_user_id_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_invitations_household_id_households')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_invitations_invited_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    op.create_table('pets',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('breed', sa.String(length=160), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('neutered', sa.Boolean(), nullable=True),
    sa.Column('weight_note', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('avatar_artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_pets_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_pets_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets'))
    )
    op.create_table('artifacts',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_artifacts_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_artifacts_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_table('behavior_events',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('antecedent', sa.Text(), nullable=False),
    sa.Column('behavior', sa.Text(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(length=20), nullable=False),
    sa.Column('intensity_source', sa.String(length=40), nullable=False),
    sa.Column('people_involved', sa.String(length=300), nullable=False),
    sa.Column('animals_involved', sa.String(length=300), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('owner_notes', sa.Text(), nullable=False),
    sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_behavior_events_pet_id_pets')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_behavior_events_recorded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behavior_events'))
    )
    op.create_index('ix_behavior_pet', 'behavior_events', ['pet_id'], unique=False)
    op.create_table('care_cards',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], name=op.f('fk_care_cards_issued_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_care_cards_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_cards'))
    )
    op.create_table('care_tasks',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repeat_rule', sa.String(length=10), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_care_tasks_assignee_user_id_users')),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], name=op.f('fk_care_tasks_completed_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_care_tasks_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_care_tasks_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_tasks'))
    )
    op.create_index('ix_care_tasks_pet_due', 'care_tasks', ['pet_id', 'due_at'], unique=False)
    op.create_table('consents',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_consents_pet_id_pets')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_consents_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('pet_id', 'purpose', name=op.f('uq_consents_pet_id'))
    )
    op.create_table('deletion_requests',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_deletion_requests_pet_id_pets')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_deletion_requests_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_requests'))
    )
    op.create_table('emergency_profiles',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('owner_contact', sa.String(length=200), nullable=False),
    sa.Column('backup_contact', sa.String(length=200), nullable=False),
    sa.Column('vet_clinic_name', sa.String(length=200), nullable=False),
    sa.Column('vet_clinic_phone', sa.String(length=60), nullable=False),
    sa.Column('vet_clinic_address_text', sa.Text(), nullable=False),
    sa.Column('critical_care_notes', sa.Text(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_emergency_profiles_pet_id_pets')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_emergency_profiles_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_profiles')),
    sa.UniqueConstraint('pet_id', name=op.f('uq_emergency_profiles_pet_id'))
    )
    op.create_table('grants',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_grants_granted_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_grants_pet_id_pets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grants'))
    )
    op.create_index('ix_grants_user_pet', 'grants', ['user_id', 'pet_id'], unique=False)
    op.create_table('health_events',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('onset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_text', sa.String(length=120), nullable=False),
    sa.Column('eating', sa.String(length=20), nullable=False),
    sa.Column('drinking', sa.String(length=20), nullable=False),
    sa.Column('elimination', sa.String(length=20), nullable=False),
    sa.Column('activity', sa.String(length=20), nullable=False),
    sa.Column('current_meds_text', sa.Text(), nullable=False),
    sa.Column('relevant_history_text', sa.Text(), nullable=False),
    sa.Column('owner_notes', sa.Text(), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_triage_level', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], name=op.f('fk_health_events_opened_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_health_events_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_events'))
    )
    op.create_index('ix_health_events_pet', 'health_events', ['pet_id'], unique=False)
    op.create_table('life_events',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('provenance_level', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supersedes_event_id', sa.UUID(), nullable=True),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_life_events_actor_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_life_events_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_events')),
    sa.UniqueConstraint('pet_id', 'idempotency_key', name='uq_lifeevent_idem')
    )
    op.create_index('ix_life_events_pet_time', 'life_events', ['pet_id', 'occurred_at'], unique=False)
    op.create_index('ix_life_events_pet_type', 'life_events', ['pet_id', 'event_type'], unique=False)
    op.create_table('relationships',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_relationships_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_relationships_pet_id_pets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_relationships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('pet_id', 'user_id', name=op.f('uq_relationships_pet_id'))
    )
    op.create_table('share_tokens',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_share_tokens_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_share_tokens_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_share_tokens_token_hash'))
    )
    op.create_index('ix_share_tokens_resource', 'share_tokens', ['resource_type', 'resource_id'], unique=False)
    op.create_table('care_handoffs',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_user_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('grant_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], name=op.f('fk_care_handoffs_caregiver_user_id_users')),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], name=op.f('fk_care_handoffs_grant_id_grants')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_care_handoffs_owner_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_care_handoffs_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_handoffs'))
    )
    op.create_table('clinical_intake_steps',
    sa.Column('health_event_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=80), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('asked_by', sa.String(length=10), nullable=False),
    sa.Column('ai_inference_id', sa.UUID(), nullable=True),
    sa.Column('answered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answered_by_user_id'], ['users.id'], name=op.f('fk_clinical_intake_steps_answered_by_user_id_users')),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('fk_clinical_intake_steps_health_event_id_health_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_intake_steps'))
    )
    op.create_index('ix_intake_steps_event', 'clinical_intake_steps', ['health_event_id'], unique=False)
    op.create_table('medication_plans',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('health_event_id', sa.UUID(), nullable=True),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dose_text', sa.String(length=200), nullable=False),
    sa.Column('route', sa.String(length=60), nullable=False),
    sa.Column('frequency_text', sa.String(length=120), nullable=False),
    sa.Column('frequency_per_day', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_note', sa.String(length=300), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_medication_plans_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('fk_medication_plans_health_event_id_health_events')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_medication_plans_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_plans'))
    )
    op.create_index('ix_med_plans_pet', 'medication_plans', ['pet_id'], unique=False)
    op.create_table('observations',
    sa.Column('health_event_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('ai_inference_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_observations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('fk_observations_health_event_id_health_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    op.create_index('ix_observations_event', 'observations', ['health_event_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('health_event_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('fk_outcomes_health_event_id_health_events')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_outcomes_pet_id_pets')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_outcomes_recorded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    op.create_index('ix_outcomes_event', 'outcomes', ['health_event_id'], unique=False)
    op.create_table('triage_assessments',
    sa.Column('health_event_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('engine', sa.String(length=30), nullable=False),
    sa.Column('matched_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_engine_version', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_triage_assessments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('fk_triage_assessments_health_event_id_health_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triage_assessments'))
    )
    op.create_index('ix_triage_event', 'triage_assessments', ['health_event_id'], unique=False)
    op.create_table('vet_briefs',
    sa.Column('health_event_id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('ai_inference_id', sa.UUID(), nullable=True),
    sa.Column('engine_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], name=op.f('fk_vet_briefs_generated_by_user_id_users')),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], name=op.f('fk_vet_briefs_health_event_id_health_events')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_vet_briefs_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vet_briefs'))
    )
    op.create_table('medication_doses',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('given_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['given_by_user_id'], ['users.id'], name=op.f('fk_medication_doses_given_by_user_id_users')),
    sa.ForeignKeyConstraint(['plan_id'], ['medication_plans.id'], name=op.f('fk_medication_doses_plan_id_medication_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_doses')),
    sa.UniqueConstraint('plan_id', 'planned_at', name=op.f('uq_medication_doses_plan_id'))
    )
    op.create_index('ix_med_doses_due', 'medication_doses', ['planned_at', 'status'], unique=False)
    op.create_index('ix_med_doses_plan', 'medication_doses', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_med_doses_plan', table_name='medication_doses')
    op.drop_index('ix_med_doses_due', table_name='medication_doses')
    op.drop_table('medication_doses')
    op.drop_table('vet_briefs')
    op.drop_index('ix_triage_event', table_name='triage_assessments')
    op.drop_table('triage_assessments')
    op.drop_index('ix_outcomes_event', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index('ix_observations_event', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_med_plans_pet', table_name='medication_plans')
    op.drop_table('medication_plans')
    op.drop_index('ix_intake_steps_event', table_name='clinical_intake_steps')
    op.drop_table('clinical_intake_steps')
    op.drop_table('care_handoffs')
    op.drop_index('ix_share_tokens_resource', table_name='share_tokens')
    op.drop_table('share_tokens')
    op.drop_table('relationships')
    op.drop_index('ix_life_events_pet_type', table_name='life_events')
    op.drop_index('ix_life_events_pet_time', table_name='life_events')
    op.drop_table('life_events')
    op.drop_index('ix_health_events_pet', table_name='health_events')
    op.drop_table('health_events')
    op.drop_index('ix_grants_user_pet', table_name='grants')
    op.drop_table('grants')
    op.drop_table('emergency_profiles')
    op.drop_table('deletion_requests')
    op.drop_table('consents')
    op.drop_index('ix_care_tasks_pet_due', table_name='care_tasks')
    op.drop_table('care_tasks')
    op.drop_table('care_cards')
    op.drop_index('ix_behavior_pet', table_name='behavior_events')
    op.drop_table('behavior_events')
    op.drop_table('artifacts')
    op.drop_table('pets')
    op.drop_table('invitations')
    op.drop_table('household_members')
    op.drop_table('users')
    op.drop_index('ix_notifications_household', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('households')
    op.drop_index('ix_audit_pet_time', table_name='audit_entries')
    op.drop_index('ix_audit_household_time', table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_table('ai_inference_logs')
    # ### end Alembic commands ###
