"""ga hardening: field_privacy, signature_status, service checklist, capability registry

Revision ID: 9b0058ac2e82
Revises: e8718b28c1eb
Create Date: 2026-09-13 12:49:52.058500
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9b0058ac2e82'
down_revision: Union[str, None] = 'e8718b28c1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_registry',
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('feature_flag', sa.String(length=80), nullable=False),
    sa.Column('contract_version', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_registry')),
    sa.UniqueConstraint('capability', 'provider', name=op.f('uq_capability_registry_capability'))
    )
    op.add_column('health_records', sa.Column('signature_status', sa.String(length=20), nullable=False, server_default='NOT_REQUIRED'))
    op.alter_column('health_records', 'signature_status', server_default=None)
    op.add_column('pets', sa.Column('field_privacy', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.alter_column('pets', 'field_privacy', server_default=None)
    op.add_column('service_requests', sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.alter_column('service_requests', 'checklist', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'checklist')
    op.drop_column('pets', 'field_privacy')
    op.drop_column('health_records', 'signature_status')
    op.drop_table('capability_registry')
    # ### end Alembic commands ###
