"""pets.lifecycle_status (PLI-013)

Revision ID: b267c90f7267
Revises: 54591ad33a24
Create Date: 2026-09-13 04:24:14.429662
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'b267c90f7267'
down_revision: Union[str, None] = '54591ad33a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'pets',
        sa.Column('lifecycle_status', sa.String(length=20), nullable=False,
                  server_default='ACTIVE'),
    )
    # backfill existing rows explicitly, then drop the default for a clean schema
    op.execute("UPDATE pets SET lifecycle_status = 'ACTIVE' WHERE lifecycle_status IS NULL")
    op.alter_column('pets', 'lifecycle_status', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'lifecycle_status')
    # ### end Alembic commands ###
