"""v1.0 schema (stage C)

Revision ID: e8718b28c1eb
Revises: ee3419e866eb
Create Date: 2026-09-13 05:15:06.790348
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e8718b28c1eb'
down_revision: Union[str, None] = 'ee3419e866eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_logs',
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('action_class', sa.String(length=40), nullable=False),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_result', sa.String(length=30), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_action_logs'))
    )
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('key', name=op.f('uq_feature_flags_key'))
    )
    op.create_table('experiment_assignments',
    sa.Column('experiment_key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_experiment_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_assignments')),
    sa.UniqueConstraint('experiment_key', 'user_id', name=op.f('uq_experiment_assignments_experiment_key'))
    )
    op.create_table('merge_requests',
    sa.Column('pet_id_a', sa.UUID(), nullable=False),
    sa.Column('pet_id_b', sa.UUID(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_merge_requests_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merge_requests'))
    )
    op.create_table('automation_rules',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_automation_rules_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_automation_rules_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_rules'))
    )
    op.create_table('behavior_intervention_plans',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('behavior_event_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('approach', sa.String(length=40), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_behavior_intervention_plans_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_behavior_intervention_plans_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behavior_intervention_plans'))
    )
    op.create_table('insurance_policy_records',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('policy_no', sa.String(length=80), nullable=False),
    sa.Column('insurer_note', sa.String(length=200), nullable=False),
    sa.Column('coverage_note', sa.String(length=300), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_insurance_policy_records_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_insurance_policy_records_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_policy_records'))
    )
    op.create_table('pet_devices',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('device_key', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('linked_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_by_user_id'], ['users.id'], name=op.f('fk_pet_devices_linked_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_devices_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_devices')),
    sa.UniqueConstraint('pet_id', 'device_key', name=op.f('uq_pet_devices_pet_id'))
    )
    op.create_table('professional_links',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('profession', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('credential_note', sa.String(length=300), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_professional_links_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_professional_links_pet_id_pets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_professional_links_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_links'))
    )
    op.create_table('service_requests',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('service_kind', sa.String(length=40), nullable=False),
    sa.Column('needs_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('care_card_id', sa.UUID(), nullable=True),
    sa.Column('provider_note', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_requests_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_service_requests_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_requests'))
    )
    op.create_table('transfer_requests',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_transfer_requests_from_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_transfer_requests_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_requests'))
    )
    op.create_table('welfare_observations',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_welfare_observations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_welfare_observations_pet_id_pets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_welfare_observations'))
    )
    op.create_index('ix_welfare_obs_pet', 'welfare_observations', ['pet_id'], unique=False)
    op.create_table('welfare_profiles',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_welfare_profiles_pet_id_pets')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_welfare_profiles_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_welfare_profiles')),
    sa.UniqueConstraint('pet_id', name=op.f('uq_welfare_profiles_pet_id'))
    )
    op.create_table('device_events',
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=False),
    sa.Column('event_kind', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('quality_note', sa.String(length=200), nullable=False),
    sa.Column('attribution', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['pet_devices.id'], name=op.f('fk_device_events_device_id_pet_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_events')),
    sa.UniqueConstraint('provider', 'provider_event_id', name=op.f('uq_device_events_provider'))
    )
    op.create_index('ix_device_events_pet_time', 'device_events', ['pet_id', 'occurred_at'], unique=False)
    op.create_table('household_expense_splits',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('share', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_household_expense_splits_expense_id_expenses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_expense_splits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_expense_splits')),
    sa.UniqueConstraint('expense_id', 'user_id', name=op.f('uq_household_expense_splits_expense_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household_expense_splits')
    op.drop_index('ix_device_events_pet_time', table_name='device_events')
    op.drop_table('device_events')
    op.drop_table('welfare_profiles')
    op.drop_index('ix_welfare_obs_pet', table_name='welfare_observations')
    op.drop_table('welfare_observations')
    op.drop_table('transfer_requests')
    op.drop_table('service_requests')
    op.drop_table('professional_links')
    op.drop_table('pet_devices')
    op.drop_table('insurance_policy_records')
    op.drop_table('behavior_intervention_plans')
    op.drop_table('automation_rules')
    op.drop_table('merge_requests')
    op.drop_table('experiment_assignments')
    op.drop_table('feature_flags')
    op.drop_table('agent_action_logs')
    # ### end Alembic commands ###
