"""care_handoffs.checklist + notifications.target_role (PLI-039/047)

Revision ID: ee3419e866eb
Revises: b267c90f7267
Create Date: 2026-09-13 04:30:48.832480
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ee3419e866eb'
down_revision: Union[str, None] = 'b267c90f7267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_handoffs', sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('notifications', sa.Column('target_role', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'target_role')
    op.drop_column('care_handoffs', 'checklist')
    # ### end Alembic commands ###
